services: 
  postgres_postgis_osm:
    build: ./  # Укажите путь к директории, где находится ваш Dockerfile для PostgreSQL и расширений
    container_name: postgres_postgis_osm
    restart: always
    volumes:
      - postgres_osm_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./central-fed-district-latest.osm.pbf:/data/central-fed-district-latest.osm.pbf  # Монтируем файл OSM
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATA: ${POSTGRES_DATA}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_osm_data:
